name: elevate3d
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision
  - pytorch-cuda=12.1
  - cmake
  - ninja

  - pip:
    - -r requirements.txt
