name: Push Elevate3D to Replicate

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  push-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Locate cog.yaml
        id: loc
        run: |
          set -euo pipefail
          echo "Repo root: $(pwd)"
          # Find the first path that contains a file named exactly cog.yaml (at depth ≤ 3)
          COG_DIR=$(find . -maxdepth 3 -type f -name cog.yaml -printf '%h\n' | head -n1)
          if [ -z "$COG_DIR" ]; then
            echo "cog.yaml not found anywhere under repo root"; exit 1
          fi
          echo "COG_DIR=$COG_DIR" | tee -a "$GITHUB_ENV"
          echo "Found cog.yaml in: $COG_DIR"

      - name: Show contents of Cog dir
        run: |
          cd "$COG_DIR"
          pwd
          ls -al
          echo "requirements.txt present?"; test -f requirements.txt && echo "yes" || echo "no"

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        working-directory: ${{ env.COG_DIR }}
        run: |
          ls -al  # final sanity check
          cog push r8.im/miniforgestudio/elevate3d
