name: Push Elevate3D to Replicate

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  push-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Locate cog.yaml directory
        id: find
        run: |
          COG_DIR=$(find . -maxdepth 3 -type f -name cog.yaml -printf '%h\n' | head -n1)
          if [ -z "$COG_DIR" ]; then
            echo "cog.yaml not found in repo"; exit 1
          fi
          echo "Found cog.yaml in: $COG_DIR"
          echo "COG_DIR=$COG_DIR" >> $GITHUB_ENV

      - name: Inspect cog directory
        run: |
          cd "${{ env.COG_DIR }}"
          echo "Working in: $(pwd)"
          ls -al

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        working-directory: ${{ env.COG_DIR }}
        run: |
          echo "Final sanity check:"
          ls -al
          cog push r8.im/miniforgestudio/elevate3d
