name: Push Elevate3D to Replicate

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  push-model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Locate and prepare cog workspace
        run: |
          set -eux
          # Find the directory containing cog.yaml (handles nested uploads)
          COGDIR=$(find . -maxdepth 3 -type f -name cog.yaml -printf '%h\n' | head -n1)
          if [ -z "$COGDIR" ]; then
            echo "ERROR: cog.yaml not found"; exit 1
          fi
          echo "Found cog.yaml in: $COGDIR"
          # Flatten into a clean workspace to avoid any weird relative path issues
          rm -rf work
          mkdir work
          rsync -a --exclude='work' "$COGDIR"/ work/
          echo "Contents of work dir:"
          ls -al work
          # Sanity checks
          test -f work/requirements.txt
          test -f work/cog.yaml
          test -f work/predict.py

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        working-directory: work
        run: |
          echo "Final check inside workspace:"
          ls -al
          cog push r8.im/miniforgestudio/elevate3d
